fastly/Viceroy

cli/src/opts.rs
We only had the short `-C` flag to pass in a config for Viceroy, but
some people would prefer a longer `--config`. This is also useful for
those learning how to use Viceroy to know what the flags mean, rather
than their shorthand version.
Closes #3
=> Add long config flag to Viceroy

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml
We've already got some changes worth releasing, and it'd be additionally valuable to grease the wheels of our release process.
Worth noting is that we add a `CHANGELOG.md` here, in the spirit of #25.
=> 🚀 Prepare for 0.2.1 release

Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml
Follow-up to #28, bumps our in-tree versions so that they reflect what the next release will be.
=> 🐦 update crates to new development version (0.2.2)

lib/src/execute.rs
Some services can contain a very large number of functions, in particular when compiled in debug mode, so to debug them in Viceroy requires a higher limit
=> Allow more functions per wasm module

.github/workflows/test.yml
We support all Tier 1 platforms that Rust uses, but we have not been
testing that they also build on other platforms besides Linux. With this
change CI will also make sure that a build will work on these platforms
as well, letting us catch any OS specific breakages that we might not
catch developing Viceroy on our own machines.
Closes #6
=> Make GH Actions also run on MacOS and Windows

Cargo.lock, cli/src/opts.rs, lib/Cargo.toml, lib/src/error.rs, lib/src/execute.rs, lib/src/wiggle_abi/dictionary_impl.rs, lib/src/wiggle_abi/geo_impl.rs, lib/src/wiggle_abi/req_impl.rs, lib/src/wiggle_abi/uap_impl.rs
This PR addresses a few minor UI nits (reported on Slack), as well as a more significant issue: rather than panicking when an unimplemented hostcall is used, we instead yield an error back to the guest. The error reporting infrastructure will print a friendly message, though in most cases the SDK will subsequently panic.
=> 🧹 Tidy up logging and error output

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Each of these commits has there own commit that expands upon why each file was added and are worth reading on their own if one wants. Mainly this PR adds these 2 files as was laid out in #25.
Closes #25
=> Add a Code of Conduct to Viceroy and Contributing file

cli/tests/sleep.rs, lib/src/linking.rs, test-fixtures/src/bin/sleep.rs
Previously, we linked with the synchronous version of the Wasi import functions, but used the tokio implementations inside them. This led to crashes in wiggle's "dummy executor", which shouldn't be in the picture.
Now we link import functions with `wasmtime_wasi::tokio`'s implementation, which defers to the underlying async engine. And, a test is added to show that this fixes the issue.
=> Use wasmtime-wasi in async mode

Cargo.lock, README.md, cli/Cargo.toml, scripts/publish.rs
This PR addresses a couple remaining issues for release and publication to crates.io: updating the cli package name to `viceroy`, and updating the README to reflect the current state of play.
Fixes #31.
=> 🚢 update viceroy package name and README

cli/tests/trap-test/Cargo.lock
@fgsch reported this morning that builds on `main`  are currently broken. This was observed in #48, specifically in [this](https://github.com/fastly/Viceroy/runs/3103246326) CI run:
```
cd cli/tests/trap-test && cargo test fatal_error_traps --locked -- --nocapture
error: the lock file /home/runner/work/Viceroy/Viceroy/cli/tests/trap-test/Cargo.lock needs to be updated but --locked was passed to prevent this
```
Unfortunate! So, quoth the git log:
```
; git log --oneline --graph -6
*   28e4078 (HEAD -> main, origin/main) Merge pull request #45 from fastly/ajt/release-0.2.2
|\  
| * 3ab0e95 Bump crates to 0.2.3
| * a851065 Update changelog for 0.2.2
* |   e41296d Merge pull request #38 from fastly/mgattozzi/lock-it-down
|\ \  
| |/  
|/|   
| * 72ffecd Have CI use --locked flag for cargo …
```
=> 🌸 Cherry-pick `trap-test` lockfile update

cli/tests/common.rs, cli/tests/http-semantics.rs, cli/tests/upstream-async.rs, cli/tests/upstream-streaming.rs, cli/tests/upstream.rs, lib/src/config/backends.rs, lib/src/config/unit_tests.rs, lib/src/error.rs, lib/src/upstream.rs
This adds a new field to the backend definition, override_host,
allowing to override the Host header that will be sent to the
backend.
Addresses #9.
=> Allow host overrides in TOML configuration

README.md
The README was duplicating some of the contents of the official CLI docs. This PR replaces that material with pointers to the devhub docs.
=> 🧹 Eliminate duplicate documentation

Cargo.lock, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, lib/src/linking.rs
This one was easy - only one tiny API change (fuel is now a u64 instead of u32).
Wasmtime release notes: https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md#0290
=> update to wasmtime 0.29 release

cli/tests/common.rs, cli/tests/logging.rs
Found by clippy when running with `--all-targets`.
=> Fix a few more warnings from clippy

Cargo.lock, lib/src/session.rs, lib/src/wiggle_abi/body_impl.rs, lib/src/wiggle_abi/req_impl.rs, lib/src/wiggle_abi/resp_impl.rs, test-fixtures/Cargo.lock
This adds the ability for Viceroy to handle closing handles for
Response, Request, Body, and StreamingBody Handle types via the close
host calls that were added to the public ABI and internally for C@E
which has rolled out to the fleet. While this does not include any SDK
updates for the tests, I've tested this out with the new version of the
Rust SDK to make sure things work out correctly which helped find a bug
or with how I implemented it with Viceroy. With this we can still work
with old versions of the SDK and handle the new SDK as well.
Closes #64
=> Add closing functionality to Viceroy for Handles

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
This updates the CHANGELOG.md with all of the changes since our last release. We don't need to worry about updating the lockfiles since they were updated in my other PR which these changes are based on top of.
=> Release Viceroy 0.2.3

lib/src/config.rs, lib/src/config/unit_tests.rs, lib/src/error.rs
Use the filename in the output.
=> Improve error when file cannot be read

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, doc/RELEASING.md, lib/Cargo.toml
this branch intends to release a new version of Viceroy.
since our last version, we have merged #69 and #70. the former is a bug-fix worth releasing soon, so let's get it out there!
i'm following the instructions added [here](https://github.com/fastly/Viceroy/blob/main/doc/RELEASING.md), so upon approval I'll push a tag and publish the crates.
=> 📜 0.2.4 release

Cargo.lock, cli/Cargo.toml, cli/src/main.rs, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, lib/src/upstream.rs
`hyper-tls` uses `native-tls`, which behave differently on different platforms.
In particular, TLS 1.3 is not supported on Windows and macOS, which is an issue since more and more servers do not support older versions any more.
`hyper-rustls` uses `rustls`, which works consistently across platforms, and supports TLS 1.3
Fixes #74
=> Replace hyper-tls with hyper-rustls

lib/src/wiggle_abi.rs
The output is still available running viceroy with -v (verbose logging).
=> Log UnknownDictionaryItem errors using DEBUG

.github/workflows/release.yml
Fixes #87 and Fixes https://github.com/fastly/cli/issues/458
Note that `macos-11` is not the same as `macos-latest`, and is required to get a recent Xcode version.
=> GitHub Actions: add aarch64 tarballs for linux and macOS

lib/src/upstream.rs, lib/src/wiggle_abi/req_impl.rs
Previously, we were relying on subtleties of Hyper's behavior to determine the final URI and Host header for outbound requests. Unfortunately, that behavior is sensitive to a number of factors, e.g. whether we happen to be sending a request via an HTTP2 connection.
This commit changes Viceroy to canonicalize the request URI and Host header before it ever reaches Hyper. In most cases this behavior will match what Hyper would do anyway.
Fixes #89
=> Make URI and Host header semantics more explicit

Cargo.lock, cli/Cargo.toml, cli/src/main.rs, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, lib/src/error.rs, lib/src/execute.rs, lib/src/lib.rs, lib/src/session.rs, lib/src/upstream.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/req_impl.rs
Previous work (#75) moved Viceroy to using rustls for TLS, with some good benefits. However, the hyper_rustls library bakes in a fair amount of TLS configuration that we need to control more directly.
Since hyper_rustls is a very thin library, and since we already need our own Hyper connector for other reasons, I opted to just use rustls directly within Viceroy, for maximum clarity/control. The main downside is that there's a bit of boilerplate around TCP/TLS streams.
Along the way, this PR also refactors the CLI backend health checks to use the Viceroy library, rather than connecting in its own way, which will help ensure we keep those in sync.
I've confirmed that this PR:
Fixes #91 
Fixes #96
=> 🎚 Use rustls for https directly, for more control

lib/src/execute.rs
This change more closely mimics the setup we previously had with hyper_rustls, and allows Viceroy to be used even if only some root certificates could be loaded.
I believe this change will address #103, but we will have to test it to be sure.
=> 🌦 Allow partial CA store to be loaded

cli/tests/common.rs, cli/tests/trap-test/Cargo.lock, cli/tests/trap-test/Cargo.toml
**n.b.** this branch is based on #105.
this adds a few lines to `viceroy_cli::tests::common::Test::against`,
which is used to run test fixtures.
this initializes and installs a tracing subscriber for use in tests,
configured to record any events (i.e., filtering at the `trace` level)
that occur in `viceroy-lib`.
because the `with_test_writer` method is used, the subscriber will use a
writer that is compatible with `cargo test`'s input capturing, and these
verbose logs will not be seen if a test finishes successfully.
an example snippet of this output is shown below:
```
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test example_test_case ... FAILED
failures:
---- example_test_case stdout ----
Dec 16 10:39:25.802  INFO viceroy_lib::execute: handling request …
```
=> ✨ tests: install a pretty tracing subscriber

lib/src/wiggle_abi/req_impl.rs
This commit updates the ABI of C@E to the latest version so that v0.8.1
Rust SDK users will not have any crashes due to a function that does not
exist. While this hostcall exists on the fleet and had been updated
internally, we hadn't updated Viceroy to have access to it as well
through a public update. This commit brings Viceroy in line with the
current Rust SDK release and stubs out the
`auto_decompress_response_set` function for `Request` that can be
implemented for local testing in a commit. For now this will stop
clients from crashing when testing locally.
Fixes #110
In order to test I ran the sample program locally from the linked issue. Here's the output where Viceroy doesn't work vs the Viceroy from this commit:
```bash
src/fastly/fastly-test is 📦 v0.1.0 via 🦀 v1.57.0 on ☁️ …
```
=> Update ABI and stub out new function

Makefile
Fixes #108, tested while working on #107.
=> 🆕 makefile: `generate-lockfile` target

Cargo.lock, cli/tests/trap-test/Cargo.lock, lib/src/wiggle_abi/req_impl.rs, test-fixtures/Cargo.lock, test-fixtures/Cargo.toml, test-fixtures/src/bin/request.rs
I've added two tests, one which set the decompression to the default value - this should not cause a panic, and another test which sets the decompression to gzip - this should cause a panic due to it being unimplemented.
This aims to resolve #115
=> do not panic on calls to auto_decompress_response_set which are not setting the decompression to gzip

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, doc/RELEASING.md, lib/Cargo.toml
this is a release branch, for a new `0.2.9` release containing #116. this will ensure that Viceroy is compatible with the `0.8.1` version of Fastly's Compute@Edge Rust SDK.
=> 🚀 `0.2.9` release

cli/Cargo.toml
Hello,
I've define path of README in toml, to let document displayed in crate.
It aims to solve the following https://github.com/fastly/Viceroy/issues/46
=> Define README path in config toml

.github/workflows/test.yml, lib/src/execute.rs
=> Bump various limits

lib/src/execute.rs
Following https://github.com/fastly/Viceroy/issues/76
(please ignore branch/commit name...)
=> Add stat for clock runtime

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, doc/RELEASING.md, lib/Cargo.toml, test-fixtures/Cargo.lock
changes included:
- add telemetry for wall-clock duration ([#121](https://github.com/fastly/Viceroy/pull/121))
- bump various runtime limits ([#123](https://github.com/fastly/Viceroy/pull/123))
=> 🚀 `0.2.10` release

lib/src/execute.rs
if a program invokes e.g., `std::process:exit(0)`, this should not cause
confusing messages as reported in #127:
```
Jan 1 00:00:00.123 ERROR viceroy_lib::execute: WebAssembly huhu: Exited with i32 exit status 0
wasm backtrace:
0: 0x280ea - <unknown>!__wasi_proc_exit
1: 0x280f6 - <unknown>!_Exit
```
apologies for the lack of test coverage here.
this is unfortunately difficult to test, because the
`Result<(), ExecutionError>` of `ExecuteCtx::run_guest` is spawned in a
task that we do not join on later. (note: that is intentional)
the alternative of a test that checks for a particular log message felt
brittle, and this is a relatively straightfoward change.
=> 𝟎 only log non-zero exit status codes

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, doc/RELEASING.md, lib/Cargo.toml, test-fixtures/Cargo.lock
- Implement automatic decompression of gzip backend responses ([#125](https://github.com/fastly/Viceroy/pull/125))
- Remove excess logging for programs that exit with a zero exit code ([#128](https://github.com/fastly/Viceroy/pull/128))
=> 📦 Release v0.2.11

.github/workflows/test.yml, Makefile
Fixes #18.
The `trap-test` target requires a different configuration of Cargo features than the normal `test` target. When run in sequence, that means we have to rebuild the entire workspace twice on the same job. By splitting these targets into different CI jobs, they can run in parallel, hopefully reducing the overall wall time of a CI run while keeping the same test coverage.
Along the way, I also made the use of the `cargo --locked` option more consistent in the Makefile, and enforce its presence when using the CI targets.
=> 📈 Split `trap-test` into a separate CI job

.github/workflows/test.yml, cli/tests/integration/common.rs, cli/tests/integration/main.rs, cli/tests/integration/memory.rs, cli/tests/trap-test/src/main.rs, test-fixtures/return_ok.wat
This version leverages `wasmtime`'s ability to compile/run WAT directly to avoid the need to install additional tooling on the build machines, at the cost of requiring some fiddling with the test harness.
Resolves #130.
=> Add support for writing test cases directly in WAT.

.github/workflows/test.yml
While looking at the cache issue from #134, I noticed errors in the
GHA output when creating the cache tarball. Furthermore, a newer
version of the cache action existed with some improvements, for
example the ability to use multiple paths in a single step.
This PR bumps the cache action to v2, merging all the steps together
as with the official example, hopefully fixing the errors and
speeding things up.
It also includes the rustc version hash in the cache key.
=> Update cache action and unify steps

.github/workflows/test.yml
Turns out, the trap-test target creates files under a different
path so use a separate cache for it.
=> Further improve caching build artifacts

lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/typenames.witx, lib/src/config.rs, lib/src/wiggle_abi/req_impl.rs, lib/src/wiggle_abi/resp_impl.rs
This PR adds stub implementations for the new hostcalls providing custom framing header controls. Attempting to use manual controls results in an error for now.
=> Provide stubs for new framing headers settings

.github/workflows/release.yml
This will hopefully address recent failures to publish releases due to aarch64 cross-compilation packages failing to download.
=> Add `apt-get update` prior to installing Linux cross-compilation

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
- Add stubs for framing header controls, now available on C@E ([#139](https://github.com/fastly/Viceroy/pull/139))
=> 📦 Release v0.2.12

cli/tests/integration/memory.rs, test-fixtures/combined_heap_limits.wat
This fixture, written in WAT to ensure that none of our compilers do
anything too smart, allows the caller to ask it to allocate memory in
various ways: on the wasm heap, in headers, or in the response body. It
also allows the user to ask it to stall for a certain amount of time.
This is handy for testing some edge cases in resource limits.
=> Add a test fixture for pushing various memory limits.

lib/src/upstream.rs
Previously the error message said "Backend URL included a scheme" but the error looks to be because a scheme was _not_ included in the Backend URL.
This commit updates the error message to state that the scheme is missing
=> Correct error message when the Backend URL is missing a scheme

lib/compute-at-edge-abi/compute-at-edge.witx, lib/src/wiggle_abi/req_impl.rs
These stubs return errors for now, but existing programs will not call them. This solely prevents link errors.
=> 🎫 Add stubs for JA3 and WebSocket upgrade hostcalls

cli/tests/integration/common.rs, cli/tests/integration/dictionary_lookup.rs, cli/tests/integration/main.rs, lib/src/config/dictionaries.rs, lib/src/config/unit_tests.rs, lib/src/error.rs, lib/src/wiggle_abi/dictionary_impl.rs, test-fixtures/data/json-dictionary.json, test-fixtures/src/bin/dictionary-lookup.rs
Fixes #142.
:crossed_fingers: _should_ also resolve #146.
this PR implements support for inline TOML dictionaries. today, dictionaries can be configured using JSON files stored on disk. as #142 outlines, this is a smidge inconsistent with the way that we configure backends. as discussion in #146 points out, this means that running a Wasm program that accesses a dictionary entails placing files on disk.
this new inline feature allows for dictionaries to be specified _inline_ within the `fastly.toml` file itself. here is an example configuration pulled from the test coverage in this branch:
```toml
name = "inline-toml-dictionary-lookup"
description = "inline toml dictionary lookup test"
authors = ["Jill Bryson <jbryson@fastly.com>", "Rose McDowall <rmcdowall@fastly.com>"]
language = "rust" …
```
=> 💕 support for inline toml dictionaries

README.md
The only git submodule was removed a few months ago in commit 0439552a65069eca4eab16827da7f01fa4538b59, so this portion of the README is no longer necessary.
=> Fix README: No more git submodules

cli/src/main.rs, cli/src/opts.rs, lib/src/service.rs
Currently viceroy will echo the value of the `--addr` flag in the `listening on` log line it prints during startup. If you're trying to run it on any available port and bind to an address like `127.0.0.1:0`, you'll see the message `listening on http://127.0.0.1:0` in the output instead of the port that was picked by the os.
This PR moves the log line into the `ViceroyService::serve` function, and prints the value bound by hyper when starting the server instead of the one passed in on the command line.
=> Move the `listening on` log message to after the port is bound

lib/src/execute.rs
At the moment, a request logs its duration with needlessly high precision:
```
Aug 05 09:44:15.967  INFO request{id=5}: request completed in 363.058968ms
```
This change reduces the precision to a whole number, which is still precise enough to be useful to humans:
```
Aug 05 09:44:15.967  INFO request{id=5}: request completed in 363ms
```
=> Reduce precision of request duration log

cli/src/main.rs, cli/tests/integration/common.rs, lib/src/config/backends.rs, lib/src/error.rs, lib/src/execute.rs, lib/src/session.rs, lib/src/upstream.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/req_impl.rs
To get closer to parity with C@E backend configuration, we add the ability to specify a certificate hostname, distinct from both the host URI or any override host. In addition, backends can now specify whether to use SNI or not; if they do, and the cert hostname is present, it will be used for SNI.
That is slightly less flexible than C@E, which allows distinct SNI and cert hosts. That's not currently possible with the TLS implementation we're using in Viceroy, and the C@E customization is mostly used to _disable_ SNI, which we provide here using a dedicated flag.
The new backend settings are:
* `cert_host` to specify the hostname for certificate checking (and SNI, if enabled)
* `use_sni`, a boolean specifying whether to employ SNI for the backend.
Both settings are optional. If …
=> Extend backend TLS configuration with cert host and SNI

cli/tests/integration/object_store.rs, lib/src/object_store.rs
Keys in the Object Store must follow the following rules:
* Keys can contain any sequence of valid Unicode characters, of length 1-1024 bytes when UTF-8 encoded.
* Keys cannot contain Carriage Return or Line Feed characters.
* Keys cannot start with `.well-known/acme-challenge/`.
* Keys cannot be named `.` or `..`.
The last one was documented correctly in the rustdoc comment but validated incorrectly as we were checking if the key contains a `.` anywhere when we are meant to only mark invalid if the key is exactly `.` or `..`
Checking the object-store codebase we can confirm the validation is meant to be exactly `.` and `..` -- https://github.com/fastly/object-store/blob/d3da1166a69a02df43b769312f95939ba7e566f2/api/src/api/key.rs#L78-L83
We are also missing another validation rule:
>* …
=> keys can contain `.` but can not cannot be named `.` or `..`

cli/tests/integration/object_store.rs, lib/src/object_store.rs
I found this validation was missing when running the object-store tests for the js-compute-runtime project.
Here is a link to the object-store codebase which contains the same validation rule: https://github.com/fastly/object-store/blob/d3da1166a69a02df43b769312f95939ba7e566f2/api/src/api/key.rs#L92-L100
=> Add validation rule for object-store keys to confirm they do not contain the characters: [, ], *, ?, #

lib/compute-at-edge-abi/typenames.witx
The Compute@Edge version of this type is correct: it's an enumeration of exactly one of the provided values. The prior version in Viceroy appears to be an early version that never got properly updated.
=> Fixes an inconsistency between the typenames.witx in Viceroy versus Compute@Edge

cli/Cargo.toml, lib/Cargo.toml
This adds some extra metadata for both the CLI tool and the library so
that publishes to crates.io won't produce warnings and to make Viceroy
more discoverable. It also points to the correct documentation for the
CLI tool on Fastly's website for the CLI which is how most will interact
with it, whereas the lib points to `docs.rs` so that they know how to
use the library itself.
Closes #17
=> Add metadata to viceroy and viceroy-lib Cargo.toml

cli/tests/integration/dictionary_lookup.rs, lib/src/session.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/dictionary_impl.rs
The previous implementation would not make use of the fastly.toml definitions and would allow any handle be created, which is not what C@E does. This pull-requests updates Viceroy to match C@E by only creating dictionaries/config-stores handles for what is defined for the service, which for Viceroy, comes from `fastly.toml`
=> match C@E by returning FastlyStatus::Badf if a dictionary does not exist with the requested name

Cargo.lock, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, lib/src/execute.rs, test-fixtures/Cargo.lock
This builds on the work of https://github.com/fastly/Viceroy/pull/177 to do a further bump up to the 1.0.0 release of Wasmtime.
=> Bump wasmtime from 0.34.0 to 0.40.1 to 1.0.0

cli/tests/integration/common.rs, cli/tests/integration/downstream_req.rs, cli/tests/integration/http_semantics.rs, cli/tests/integration/memory.rs, cli/tests/integration/upstream.rs, cli/tests/integration/upstream_dynamic.rs
If you're already running viceroy on its default 7878 port, several
intergration tests fail because they try to bind to that port.
=> run integration tests on port 17878 to avoid port conflicts

lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/typenames.witx, lib/src/wiggle_abi/req_impl.rs
These stubs return errors for now. There is no existing program using these new calls.
=> Add stubs for mTLS info hostcalls

cli/src/main.rs, cli/src/opts.rs, cli/tests/integration/common.rs, cli/tests/trap-test/src/main.rs, lib/src/error.rs, lib/src/execute.rs, lib/src/lib.rs, lib/src/service.rs
=> Allow to enable wasmtime's profiling support

.github/workflows/release.yml, .github/workflows/test.yml
Partially addresses #193. `action-gh-release` seems to be sporadically maintained (the author merged PRs as recently as July, but the project hasn't had a release in ~a year) so it may be worth finding an alternative.
We are currently getting two deprecation warnings:
1. node12 deprecation
2. [`set-output` and `save-state` deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
Both of these warnings are coming in transitively through actions that we depend on:
- The Github provided actions that were still depending on node12 ([`actions/checkout`](https://github.com/actions/checkout/blob/main/CHANGELOG.md#v300) and [`actions/cache`](https://github.com/actions/cache#v3)) have been upgraded to `v3`
- `olegtarasov/get-tag` [has …
=> 🎬 Update github actions to avoid deprecation warnings

lib/compute-at-edge-abi/typenames.witx
This variant is returned when an attempt to allocate a resource has exceeded the maximum number of resources permitted. For example, creating too many response handles or makiing too many dictionary lookups.
=> Update fastly_status witx definition to include the new limitexceeded variant

lib/src/error.rs, lib/src/object_store.rs, lib/src/wiggle_abi/obj_store_impl.rs, test-fixtures/src/bin/object_store.rs
Currently we return an invalid handle, which seems to be different behavior than what I am seeing on C@E -- I've updated the implementation to match what I see on C@E, which is to return FastlyStatus::Inval
=> Return a FastlyStatus::Inval when opening a non-existant object-store

Makefile
A followup to #201, this removes Clippy from CI checks completely.
As @pchickey says, it's "unstable and creates a lot of CI churn."
=> remove clippy from CI checks

lib/src/config/dictionaries.rs, lib/src/config/object_store.rs, lib/src/wiggle_abi/req_impl.rs
```
cargo clippy --all -- -D warnings
Checking viceroy-lib v0.3.2 (/Users/jshaw/src/fastly/Viceroy/lib)
error: the borrowed expression implements the required traits
--> lib/src/config/dictionaries.rs:59:39
|
59 |         let data = fs::read_to_string(&file).map_err(DictionaryConfigError::IoError)?;
|                                       ^^^^^ help: change this to: `file`
|
= note: `-D clippy::needless-borrow` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
error: the borrowed expression implements the required traits
--> lib/src/config/object_store.rs:73:34
|
73 |                         fs::read(&path).map_err(|e| {
|                                  ^^^^^ help: change this to: `path`
|
= help: for …
```
=> fix clippy errors that fail CI builds

.github/workflows/release.yml, CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml
Changes since previous version from our CHANGELOG
- Add geolocation implementation to Viceroy
([#165](https://github.com/fastly/Viceroy/pull/165))
- Implement async select hostcalls for Viceroy
([#188](https://github.com/fastly/Viceroy/pull/188))
- Update wasmtime dependency to 2.0
([#194](https://github.com/fastly/Viceroy/pull/194))
- Return a FastlyStatus::Inval when opening a non-existant object-store
([#196](https://github.com/fastly/Viceroy/pull/196))
- Add limit exceeded variant to fastly_status witx definition
([#199](https://github.com/fastly/Viceroy/pull/199))
=> Release Viceroy 0.3.2

cli/tests/integration/sending_response.rs, lib/src/body.rs, lib/src/error.rs, lib/src/streaming_body.rs, lib/src/wiggle_abi/body_impl.rs, test-fixtures/Cargo.lock, test-fixtures/Cargo.toml, test-fixtures/src/bin/gzipped-response.rs, test-fixtures/src/bin/streaming-response.rs, test-fixtures/src/bin/upstream-streaming.rs
Moving forward, streaming bodies must be affirmatively finished when Wasm programs are finished writing to them. This helps prevent unexpected control flows due to error handling causing an incomplete `transfer-encoding: chunked` streaming body from appearing complete to its recipient.
These changes require updates to the integration test fixtures with a prerelease version of the SDK. Once the 0.9.0 Rust SDK is released, we'll follow up with an update to the released version.
=> 🕳 Implement `finish` semantics for streaming bodies

.github/workflows/release.yml, .github/workflows/test.yml
This should avoid pulling in breaking versions of glibc until we address #120.
=> Pin test and release runners to ubuntu-20.04

.github/workflows/release.yml, CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
This changes the release script to reestablish exclusion of arm64 windows builds in the wake of #216
=> 📦 Prepare 0.3.4 release

.github/workflows/release.yml
Fixes #112.
This adds another job to the release action, called "publish", which depends on the "build" job. The release will remain in a draft state until the entire build matrix succeeds, at which point it will get published. A successful run will look something like this:
=> Publish releases atomically

cli/Cargo.toml, cli/src/main.rs, cli/src/opts.rs, lib/src/execute.rs, lib/src/lib.rs, lib/src/linking.rs
This introduces a "run-mode" to Viceroy that will allow us to use it as a test runner. The goal is to allow developers of C@E services to use Viceroy to run unit tests that rely on things provided by Fastly's SDKs. This is based off of a proof-of-concept that @acfoltzer put together a few months ago 🙏 
To run a wasm program's `_start` function and then exit, the invocation looks like this:
```
$ viceroy -C fastly.toml --run my_program.wasm
```
This will set up the context described in `fastly.toml` and all the wasm context expected by a C@E service, and then run `_start`. If you would like to pass arguments to the wasm program, you can specify those after a `--` on the command line, like so:
```
$ viceroy -C fastly.toml --run my_program.wasm -- --arg-for-wasm-program
```
1. Add the …
=> 🏃  Add a run-mode that executes the input program once and then exits

cli/src/main.rs, cli/tests/integration/common.rs, cli/tests/integration/object_store.rs, cli/tests/integration/secret_store.rs, lib/src/config.rs, lib/src/config/object_store.rs, lib/src/config/secret_store.rs, lib/src/error.rs, lib/src/execute.rs, lib/src/object_store.rs, lib/src/session.rs
`object_store` becomes `object_stores` for consistency with `backends`
and `dictionaries`.  `path` becomes `file` for consistency with
dictionaries and geolocation config.
An example object store in the fastly.toml file might now look something
like:
```
[local_server]
object_stores.store_one = [{key = "one", file = "/path/to/something"}]
```
or
```
[local_server]
[local_server.object_stores]
store_one = [{key = "one", file = "/path/to/something"}]
```
or
```
[local_server]
[local_server.object_stores]
[[local_server.object_stores.store_one]]
key = "one"
file = "/path/to/something"
```
Backwards compatibility is maintained.
The Secret Store is updated to match the new Object Store conventions, but backwards compatibility is not maintained (because it's brand new and doesn't need to be).
=> object & secret store config naming changes for consistency

lib/src/config/dictionaries.rs, lib/src/config/limits.rs
this limit can be raised per service on c-at-e. if the limit was raised on a customers service, then the customer could no longer run their application locally with viceroy. by removing he limit in viceroy, customers who have a himit dictionary limit would be able to run their application locally.
I hit this issue in my own project which uses a dictionary containing ~3400 keys
=> fix: remove dictionary count limit from viceroy

cli/src/main.rs, cli/src/opts.rs, lib/src/execute.rs
Addresses #222.
The structure here is somewhat complex in order to get clap to behave how we want it to. Specifically:
- We would like behavior separated into `serve` and `run` subcommands, but if neither of those is provided the default behavior should be `serve` (to maintain backwards compatibility)
- Some options are only valid in `serve` mode and some are only valid in `run` mode
- Some shared options are valid in both modes
- There is a shared argument, `input`,  that is *required* regardless of the mode
The way that we accomplish having a default subcommand with clap is like this:
- Make the top level command struct contain just two arguments, one for the subcommand and one for the args for whichever subcommand is the default (`serve` in this case)
- Add …
=> 🪆 separate behavior into sub-commands, with serve being the default 

lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/typenames.witx, lib/src/error.rs, lib/src/session.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/backend_impl.rs, lib/src/wiggle_abi/req_impl.rs
This doesn't actually implement any interesting functionality -- it's not clear what pooling would mean within the context of Viceroy -- but it allows programs that use this flag to function properly.
Because this just bit me, I've also removed the bit of code that checks for unknown flags and errors. I think it actually makes more sense for old versions of Viceroy to ignore flags they don't understand. Admittedly, I'm betting that future changes will be like this one (in that they don't change any, or change very little, Viceroy behavior), and not settings which will totally change behavior.
=> 🪀 Add `fastly_backend` interfaces for backend introspection

cli/tests/integration/config_store_lookup.rs, lib/src/config.rs, lib/src/config/unit_tests.rs, test-fixtures/data/json-config_store.json
Currently they can be defined using `[local_server.dictionaries]`, this patch adds an alias for `[local_server.config_stores]` which matches the way we defined object and secret stores (`local_server.object_stores` and `local_server.secret_stores`)
=> feat: allow config-stores to be defined using `[local_server.config_stores]`

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
=>  🎁 prepare release 0.4.2

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
=>  🎁 prepare release 0.4.3 

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
=> 🎁 prepare release 0.4.4

lib/src/config/dictionaries.rs, lib/src/config/unit_tests.rs, lib/src/error.rs
The validation rules for names of Config Stores and Dictionaries are different. Config Stores have very relaxed rules, the name can contain any character, even just whitespace characters.
This patch removes the validation rules for names, this does mean an invalid Dictionary name could be used locally, but the customer will see the issue when they deploy to Fastly Compute
=> Remove validation on config store and dictionary names

.github/workflows/test.yml, cli/tests/integration/upstream_async.rs, test-fixtures/src/bin/upstream-async.rs
This allows us to observe that the implementation of `poll()` doesn't block, unlike its counterpart `wait()`.
=> 🗳️ Add synchronization logic for upstream-async tests

Cargo.toml, cli/tests/integration/async_io.rs, cli/tests/integration/common.rs, cli/tests/integration/common/backends.rs, cli/tests/integration/downstream_req.rs, cli/tests/integration/http_semantics.rs, cli/tests/integration/memory.rs, cli/tests/integration/upstream.rs, cli/tests/integration/upstream_async.rs, cli/tests/integration/upstream_dynamic.rs, cli/tests/integration/upstream_streaming.rs, cli/tests/trap-test/src/main.rs, lib/src/config/backends.rs, lib/src/execute.rs, test-fixtures/src/bin/gzipped-response.rs
No more `TEST_LOCK`! The integration tests now take less than 5 seconds to execute on my workstation, vs 79 seconds previously.
This required two main pieces of work.
The server spun up to run incoming requests through Wasm now is bound to an ephemeral port rather than being hardcoded to port 7878, and the test requests have their URLs modified to include the ephemeral port assigned to the test.
This change technically means the `Test::against*()` methods can no longer be used to send requests to destinations other than the Viceroy that's been spun up for this test, but that's the only way they're currently used anyway.
The main concrete change here for test authors is that you no longer specify `localhost:7878` in your test requests, you instead just provide a request path.
This is a …
=> 🕷️ Rework integration tests to allow parallel test execution

lib/src/wiggle_abi/backend_impl.rs
This enables applications to use is_healthy during local development without it erroring, but also without it marking backends and healthy or unhealthy
=> fix: make is_healthy always return `Unknown` instead of an unsupported error

lib/compute-at-edge-abi/cache.witx, lib/compute-at-edge-abi/compute-at-edge.witx, lib/src/linking.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/cache.rs
This adds stubs to allow programs using the unreleased Cache API to succesfully link in Viceroy. This will be followed later by a mock cache implementation.
=> 🚧 Add stubs for Cache API primitives

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
=> 🎁 prepare release 0.5.0

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml
=> 🎁 prepare release 0.5.1

lib/src/execute.rs
It was previously dropped immediately, which would cause a panic with
"response receiver is open: ()" when a response was sent.
=> in single run mode, keep the response receiver alive during execution

lib/compute-at-edge-abi/typenames.witx
The ABI expects `$none` to have a value of 0, and `$pass` to have a
value of 1.  However, flags in witx start with a value of 1.  Putting
`$none` in the list erroneously defines it to have a value of 1.
Fastly's SDKs do things correctly, but tools like https://github.com/jedisct1/witx-codegen
which generate bindings from witx will generate code that is off by one
bit position.
=> ⏩ none should not be defined in cache_override_tag witx

cli/src/main.rs, cli/src/opts.rs, lib/src/config/geolocation.rs, lib/src/config/secret_store.rs, lib/src/execute.rs, lib/src/session.rs, lib/src/streaming_body.rs, lib/src/wiggle_abi/req_impl.rs, lib/src/wiggle_abi/secret_store_impl.rs
Fix various warnings spotted by clippy.
=> Fix various warnings

lib/compute-at-edge-abi/compute-at-edge.witx, lib/src/linking.rs, lib/src/wiggle_abi/req_impl.rs
This PR adds a stub for downstream_client_request_id to avoid crashing Viceroy.
I'm not sure if it'd be better to return something meaningful. Open to suggestions.
=> Add a stub for downstream_client_request_id

lib/src/wiggle_abi/req_impl.rs
Instead of returning an empty string, use the request id to mimic prod closer. 
Prompted by @GeeWee in https://github.com/fastly/Viceroy/pull/276.
=> Fill downstream_client_request_id in

lib/compute-at-edge-abi/compute-at-edge.witx, lib/src/linking.rs, lib/src/wiggle_abi/req_impl.rs
This adds a single stub for `downstream_client_h2_fingerprint` which will allow applications using this feature to be able to link in Viceroy
=> feat: Add a stub for downstream_client_h2_fingerprint

Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, cli/tests/trap-test/Cargo.toml, lib/Cargo.toml, test-fixtures/Cargo.lock
hyper 0.14.27 changes the behavior of an empty request body with cunked encoding, which causes a regression in our particular test setup for async_io
https://github.com/hyperium/hyper/commit/32422c47ec35e7405873277c87de14c18dbb98bd
=> pin to hyper 0.14.26 for the time being

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml
Note: I've bumped from 0.5.1 to 0.6.0 due to upgrading wasmtime to a new major version (10.0.0)
> 
> 1. Create a local …
=> 🎁 prepare release 0.6.0

README.md, cli/src/opts.rs, cli/tests/trap-test/src/main.rs, lib/src/config/unit_tests.rs
I think this would be viewed as a breaking change as we are changing the default behaviour of the CLI.
If that is the case, then this involves bumping from 0.6.0 to 0.7.0 when it comes to releasing this
Resolves https://github.com/fastly/Viceroy/issues/47
=> Change default port from 7878 to 7676, which is what the Fastly CLI defaults to

Cargo.lock, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, lib/src/upstream.rs, test-fixtures/Cargo.lock
Bump the rustls, rustls-native-certs, and tokio-rustls versions to their latest. This drops the need for the webpki dependency for the rustls-webpki fork, which brings in many bug fixes for X.509 certificate handling. Additionally, the [trusted CA anchors can be specified via the `SSL_CERT_FILE` environment variable](https://github.com/rustls/rustls-native-certs#release-history).
=> Update rustls and various dependencies

cli/src/main.rs, cli/src/opts.rs
The previous default log level was "off", which meant that errors
encountered during startup with `viceroy run` were not printed and the
process silently failed.  For example, this might happen if you had an
invalid path in your `fastly.toml` file.
In addition, there was no way to turn on verbose log output with
`viceroy run`, only in serve mode.
This commit moves the default log level to "error", and moves the `-v`
flag into the common set.
Making "error" the default meant that processes that called `proc_exit`
would print WASM stacktraces as errors on exit, but this isn't really an
error from the user's perspective, so we check for that (`I32Exit`) and
suppress the error message in that case only.
=> switch default log level to "error", add -v to run

lib/src/error.rs
This matches the Compute@Edge behavior.
=> Error::ValueAbsent should map to FastlyStatus::None, not Inval

lib/src/error.rs
This is better than a generic error, and matches the C@E behavior.
Fixes #289.
=> when an upstream body is unexpectedly closed, return Httpincomplete

lib/src/error.rs
This matches C@E behavior.
Fixes #292.
=> map Error::UnknownBackend to FastlyStatus::Inval

lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/config-store.witx, lib/src/linking.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/config_store.rs
These work by naively just forwarding the new hostcalls into the underlying dictionary system; these pass the tests, but I'd love someone to confirm (preferably someone named @acfoltzer) that this is intended behavior.
=> Support the new config store hostcalls.

lib/src/execute.rs, lib/src/linking.rs
Instead of counting the number of pages present in the memory exported by a wasm module, count the memory allocation diffs over time using the `ResourceLimiter` api.
This change helps set us up for component support, as there's no analogue of `get_memory` for components.
=> Use a ResourceLimiter for tracking allocations

lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/typenames.witx, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/body_impl.rs, lib/src/wiggle_abi/req_impl.rs
Adds several new hostcalls and type definitions to the ABI. The level of implementation varies:
- `fastly_http_body::abandon` is fully implemented.
- `fastly_http_req::send_v2` and friends will work, but do not yet populate the new `$error_detail` field with information about the failure.
- `fastly_http_req` hostcalls `downstream_client_oh_fingerprint`, `redirect_to_websocket_proxy_v2`, `redirect_to_grip_proxy_v2`, and `fastly_key_is_valid` are stubs that return `Error::NotAvailable`.
Beyond these added functions, there are a number of formatting fixes in the witx to make the Viceroy copy of these files more precisely match what we use internally to define the platform.
=> 🌭 Update ABI definitions and stub out some hostcalls

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, lib/src/error.rs, test-fixtures/Cargo.lock
Includes a sneaky `#[non_exhaustive]` annotation on `viceroy_lib::Error` to prevent future new variants from requiring major version bumps.
=> 📦 Prepare 0.8.0 release

lib/src/wiggle_abi.rs
The Fastly CLI executes Viceroy with a [`-v`](https://github.com/fastly/cli/blob/24761dcccd81d16e3873c1fa65e03fd83486442f/pkg/commands/compute/serve.go#L534) argument, which corresponds to `INFO` log level. This change drops the log level of hostcall errors to `DEBUG`, so that they're not displayed to users running apps via `fastly compute serve`.
As an example, `BufferLengthError` is a sentinel error used to indicate to the caller that the passed in buffer was [too small](https://github.com/fastly/Viceroy/blob/f62eb94c470f39df1d25cba3ffb028a3289bbf15/lib/src/wiggle_abi/secret_store_impl.rs#L110-L113). The caller can then try again with an appropriately sized buffer.
=> Lower Hostcall error log level to DEBUG

Cargo.lock, Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/src/execute.rs, lib/src/linking.rs, test-fixtures/Cargo.lock
Bump the wasmtime dependency to 13.0.0.
There were changes to the pooling allocator config needed, as well as the initialization of the wasi-nn context. It looks like we're currently not providing a way to load any models into the wasi-nn context, so I've initialized it with none.
=> Update to wasmtime-13.0.0

cli/src/opts.rs
This syncs the available profiling strategies with those in wasmtime.
=> Add perfmap profiling strategy

cli/src/main.rs, cli/src/opts.rs, lib/src/execute.rs
This PR moves profiling to `--profile`, and replaces `--profile-guest=[path]` in favour of `--profile=guest[,path]`, unifying the profiling options (and matching Wasmtime). Most of the code is adapted from Wasmtime.
While here I've removed some unncessary lifetimes and polished the code, mostly courtesy of clippy (the 2 last commits).
The PR is related to and was built on top of https://github.com/fastly/Viceroy/pull/316. It might make sense to review that one first.
=> Revamp profile handling CLI flags

lib/src/execute.rs
Fix a bug introduced with the upgrade to wasmtime-13.0.0 where the maximum number of memories was set to `1`. This should have matched the number of core instances we allow, as we permit one memory per core instance.
Fixes #321
=> Match the number of memories to the number of core instances

CHANGELOG.md, Cargo.lock, cli/tests/trap-test/Cargo.lock
> 
>    the major, minor, and patch …
=> 🎁 prepare release 0.9.1

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml
https://github.com/fastly/Viceroy/pull/323 was merged before the second half of the release process was completed - this pull request contains that second half of the process
=> Finish release process for 0.9.1 by bumping to next patch and updating lockfiles and changelog

lib/src/upstream.rs
A user running Viceroy on Windows hit this `unwrap()` call when trying out the rust compute starter kit:
```
c:\dev\source\fastly-from-scratch>fastly compute serve
✓ Verifying fastly.toml
✓ Identifying package name
✓ Identifying toolchain
✓ Running [scripts.build]
✓ Creating package archive
SUCCESS: Built package (pkg\fastly-from-scratch.tar.gz)
✓ Running local server
INFO: Listening on http://127.0.0.1:7676/
INFO: Command output:
--------------------------------------------------------------------------------
thread 'main' panicked at lib\src\upstream.rs:50:61:
called `Result::unwrap()` on an `Err` value: InvalidCertificate(BadEncoding)
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace. …
```
=> Warn instead of fail when certificates can't be loaded

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
> 
>    the major, minor, and patch …
=> 🎁 prepare release 0.9.2

lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/typenames.witx, lib/src/error.rs, lib/src/session.rs, lib/src/session/async_item.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/obj_store_impl.rs
Adding in response to some nudging by @dcaba
=> Add async inserts for kv store

cli/tests/integration/edge_rate_limiting.rs, cli/tests/integration/main.rs, lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/typenames.witx, lib/src/linking.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/erl_impl.rs, test-fixtures/src/bin/edge-rate-limiting.rs
Add hostcalls for edge rate limiting.
The test that executes the hostcalls needs a new SDK, so is commented out in this PR. The test passes locally when built with the new SDK.
=> Add edge rate limiting hostcalls

lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/typenames.witx, lib/src/error.rs, lib/src/object_store.rs, lib/src/session.rs, lib/src/session/async_item.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/obj_store_impl.rs
Tested good on the local machine with an sdk which also has the hostcall
=> Add delete_async hostcall for kv

lib/src/linking.rs, test-fixtures/src/bin/env-vars.rs
We already had a few here, with values that make sense. I expect these ones were missing because their values don't make sense, I'm just hardcoding something reasonable. What matters for me is that they're present at all, and to match production ecp in what's present.
My intention is that a user would then be able to override these stub values by explicitly setting things from the config file (see https://github.com/fastly/Viceroy/issues/336 about that), but that there's no way to ever have these not set. Because that matches production.
=> Add stubbed-out values for remaining `FASTLY_` environment variables.

lib/src/error.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/geo_impl.rs
This matches the Fastly Compute behavior.
As a result, we don't need the `GeolocationError` type anymore and this
commit also removes it.
Fixes #339.
=> return an empty result when geolocation data is not found

Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.toml, test-fixtures/src/bin/edge-rate-limiting.rs
This test was originally landed in the ERL (Edge Rate Limiting) [pull-request](https://github.com/fastly/Viceroy/pull/333) but commented out as the SDK with the feature implemented had not yet been released.
Now that the SDK has been released, we can bump up the minimum version of the SDK used in the tests and uncomment the ERL test to confirm that it is working as expected (and to catch any possible future regressions)
=> ⏫ Bump up the Fastly SDK to latest version and uncomment the test for the Edge Rate Limiting API

test-fixtures/src/bin/device-detection-lookup.rs
The SDK version which has the device detection functionality has been released, meaning we can uncomment this now
=> uncomment device detection test app

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
> 
>    the major, minor, and patch …
=> 🎁 prepare release 0.9.5

lib/src/wiggle_abi/req_impl.rs, test-fixtures/src/bin/downstream-req.rs
> [!NOTE]  
> This is blocked, waiting on a new release of the fastly crate
Currently these functions return a NotAvailable error, I believe this is because we don't support https within Viceroy.
We do support http though, and http is also supported on Fastly, this patch adds an implementation for the downstream-tls functions which is valid for http (non-tls) connections. As Viceroy does not yet support https, we _could_ say this is a full implementation as-of-today.
In the future if/when Viceroy supports https, we would need to come back to these functions and make them return the correct, expected values based on the incoming connection (tls or not), which is why I have left "FIXME" comments on all of these.
=> Return a ValueAbsent for all the downstream-tls related functions instead of a NotAvailable

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
> 
>    the major, minor, and patch …
=> 🎁 prepare release 0.9.6

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/main.rs, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, lib/src/execute.rs, lib/src/linking.rs, lib/src/logging.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/backend_impl.rs, lib/src/wiggle_abi/body_impl.rs, lib/src/wiggle_abi/device_detection_impl.rs, lib/src/wiggle_abi/dictionary_impl.rs, lib/src/wiggle_abi/geo_impl.rs, lib/src/wiggle_abi/headers.rs, lib/src/wiggle_abi/obj_store_impl.rs, lib/src/wiggle_abi/req_impl.rs, lib/src/wiggle_abi/secret_store_impl.rs, test-fixtures/Cargo.lock
Update the wasmtime dependency to wasmtime-20, and also remove the dependency on wasi-common in favor of using the preview1-on-preview2 implementation provided by wasmtime-wasi.
There was also a change in wiggle's borrow checker for the 20.0.0 release that affected our host call implementations directly: borrows are no longer to a region, but the whole guest memory. This caused a bit of churn in the wiggle_abi tree, and I'm not completely certain that all issues have been resolved, as the test suite can only test so many paths through the host calls. For reference, here's the wiggle refactoring PR in wasmtime: https://github.com/bytecodealliance/wasmtime/pull/8277.
=> Upgrade to wasmtime-20, and switch to wasmtime-wasi

lib/src/component/http_req.rs, lib/src/component/http_resp.rs, lib/src/wiggle_abi/headers.rs
Make the handling of header values given to the `header-values-set` functions in the component implementation consistent with the existing wiggle implementation. Additionally, use `next_back` instead of reversing and skipping the first element.
=> Fix header_values_set handling in the component implementation

Cargo.lock, Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/src/component/mod.rs, test-fixtures/Cargo.lock
Update to wasmtime 21.0.0.
The most substantial changes were to the use of the `component::bindgen!` macro, which now no longer automatically generates host bindings that are allowed to trap. Additionally, the generated `add_to_linker` functions are no longer present, and we instead need to use `add_to_linker_get_host`, which requires a new projection function to be supplied.
=> Update to wasmtime-21

lib/src/component/async_io.rs, lib/src/component/backend.rs, lib/src/component/cache.rs, lib/src/component/dictionary.rs, lib/src/component/error.rs, lib/src/component/geo.rs, lib/src/component/http_body.rs, lib/src/component/http_req.rs, lib/src/component/http_resp.rs, lib/src/component/kv_store.rs, lib/src/component/log.rs, lib/src/component/mod.rs, lib/src/component/purge.rs, lib/src/component/secret_store.rs, lib/src/component/types.rs, lib/src/component/uap.rs, lib/wit/deps/fastly/compute.wit
The `trappable_error_type` argument to `wasmtime::bindgen!` became optional in wasmtime-21, and given that we never expect to trap in any of our host implementations, let's remove that additional complexity.
The meat of this change is removing the custom `FastlyError` type, and replacing it with `types::Error` which is generated from compute.wit. This simplifies some functions like the `v2` suffixed request functions, but in most cases ended up being a renaming from `FastlyError` to `types::Error`.
=> Remove the trappable_error_type

lib/src/execute.rs, lib/src/session.rs
`ObjectStores` internally is an `Arc` to an `RwLock`, so the outer `Arc` present in `Session` is not necessary. This PR removes that unnecessary indirection, as `ObjectStore` already derives `Clone`.
=> Remove an unnecessary Arc from the Session

lib/compute-at-edge-abi/cache.witx, lib/src/component/cache.rs, lib/src/wiggle_abi/cache.rs, lib/wit/deps/fastly/compute.wit
As with existing caching APIs, these are just stubs for now, needed to support new SDK releases.
=> Add stubs for new "busy handle" APIs for the core cache

lib/src/component/kv_store.rs, lib/wit/deps/fastly/compute.wit
Modify the definition of the `open` function in the `kv-store` interface to return an optional handle instead of wrapping that case into the error.
=> Have kv-store#open return an optional handle

lib/src/component/config_store.rs, lib/src/component/dictionary.rs, lib/src/config.rs, lib/src/config/dictionaries.rs, lib/src/config/unit_tests.rs, lib/src/session.rs, lib/src/wiggle_abi/dictionary_impl.rs
Read dictionaries during the `open` host call instead of once for each `get` call. This improves viceroy performance for large dictionaries, and more closely matches the semantics of the production environment, as changes made while the dictionary is open won't be reflected in subsequent `get` calls.
Additionally, remove the `DictionaryName` newtype, as it wasn't offering anything over using a `String` directly.
co-authored-by: Jamey Sharp <jsharp@fastly.com>
=> Switch to reading dictionaries during the `fastly_dictionary_open` call

lib/src/wiggle_abi/device_detection_impl.rs, lib/src/wiggle_abi/geo_impl.rs
Write out the required buffer size to the nwritten_out value if the
buffer is too small to fit the value.
=> add adaptive buffer support for geo + device detection lookups

cli/tests/trap-test/src/main.rs, lib/src/component/http_req.rs, lib/src/component/http_resp.rs, lib/src/component/mod.rs, lib/src/component/types.rs, lib/src/execute.rs
The component implementation didn't have support for either the `test-fatalerror-config` feature, or the ability to treat the `Error::FatalError` variant as a trap. This PR fixes that by doing the following:
* Allowing `header_values_get` to trap based on the `test-fatalerror-config` feature
* Introducing the `TrappableError` type for treating `FatalError` as a trap
* Adding a variant of the `trap-test` that uses the component adapter
The remaining difference to the wiggle implementation is that only functions listed in `trappable_errors` will be able to emit traps for `FatalError`, though the only case we currently use that in is for `test-fatalerror-config`, so it seemed reasonable to not switch everything to `TrappableError`.
=> Fix trap handling when running components

cli/tests/integration/request.rs, lib/src/component/headers.rs, lib/src/component/http_body.rs, lib/src/component/http_req.rs, lib/src/component/http_resp.rs, lib/src/component/types.rs, test-fixtures/src/bin/request.rs
Run request tests with components. This required changes to the long_header cases in `request.wasm`, as the strings passed need to be valid with the canonical abi.
=> Run the `request` tests as a component

cli/tests/integration/config_store_lookup.rs, cli/tests/integration/main.rs, test-fixtures/src/bin/config-store-lookup.rs
The tests in `cli/tests/integration/config_store_lookup.rs` weren't being run because the module wasn't declared in `cli/tests/integration/main.rs`. I've re-enabled them, and copied the dictionary-lookup.rs test fixture to `config-store-lookup.rs`, to allow them to run successfully.
=> Enable the config-store-lookup tests

test-fixtures/src/bin/dictionary-lookup.rs
The dictionary fixture is using the `ConfigStore` api from the fastly crate, which uses the config-store host calls under the hood. To ensure that we're testing the dictionary host calls while they exist, this PR refactors the dictionary-lookup fixture to use the dictionary host calls directly.
=> 🔧 Explicitly test the dictionary host calls in the dictionary fixture

lib/src/execute.rs, lib/src/linking.rs
Fixes #255.
In addition to just fixing #255, this also allows the test suite to be run in parallel, again. At least on my machines, running `make test` directly would cause memory failures. I'm guessing this was due to the pooling allocator's use of virtual memory. Switching to the on-demand allocator means that things run fine.
This extends the built-in `Limiter` object to use a `StoreLimits` under the hood, as suggested in the issue. It then builds different versions of this limiter based on whether or not Viceroy is operating in a component or non-component context, because component-based systems require more instances and more tables than traditional ones.
=> ⁉️ Switch to using the on-demand allocator, instead of the pooling allocator

lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/config-store.witx, lib/src/wiggle_abi/config_store.rs, lib/src/wiggle_abi/dictionary_impl.rs, test-fixtures/src/bin/config-store-lookup.rs, test-fixtures/src/bin/dictionary-lookup.rs
The wiggle representation of a function that returns `Result<u32, FastlyStatus>` and one that takes a `u32` outparam as its last argument and returns `Result<(), FastlyStatus>` are the same, which means that we can support communicating the length needed to resolve a `FastlyStatus::BufferLen` error without changing the abi of `fastly_config_store::get` or `fastly_dictionary::get`.
This PR makes this change to both `fastly_config_store::get` and `fastly_dictionary::get`, allowing SDKs to better adapt when buffer-length errors occur.
=> 🎁 Populate nwritten_out when errors occur in config-store::get or dictionary::get

Cargo.lock, Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/src/async_io.rs, lib/src/component/mod.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/backend_impl.rs, lib/src/wiggle_abi/body_impl.rs, lib/src/wiggle_abi/cache.rs, lib/src/wiggle_abi/config_store.rs, lib/src/wiggle_abi/device_detection_impl.rs, lib/src/wiggle_abi/dictionary_impl.rs, lib/src/wiggle_abi/erl_impl.rs, lib/src/wiggle_abi/fastly_purge_impl.rs, lib/src/wiggle_abi/geo_impl.rs, lib/src/wiggle_abi/headers.rs, lib/src/wiggle_abi/log_impl.rs, lib/src/wiggle_abi/obj_store_impl.rs, lib/src/wiggle_abi/req_impl.rs, lib/src/wiggle_abi/resp_impl.rs, lib/src/wiggle_abi/secret_store_impl.rs, lib/src/wiggle_abi/uap_impl.rs, test-fixtures/Cargo.lock
Update to wasmtime 22.0.0.
This included some pretty substantial changes to the wiggle crate, which removes
runtime borrow checking of guest memory. This is a huge ergonomic improvement,
as the borrows are all tracked as rrust borrows instead.
One piece of functionality that's missing after the wiggle changes is the
ability to interact with a slice of guest memory that's not `&[u8]`. To work
around this, I'm copying memory over to the host, but in future releases of
wiggle we should have the ability to interact with slices that aren't just to
`u8`.
=> 🎁 Update to wasmtime 22.0.0

cli/tests/integration/args.rs, cli/tests/integration/main.rs, lib/src/component/http_resp.rs, lib/src/execute.rs, lib/wit/deps/fastly/compute.wit, test-fixtures/src/bin/args.rs
Populate the guest cli args with the single value `"compute-app"`. This should simplify adoption for languages that assume the args list is non-empty.
Fixes #376
=> 🔨 Populate the guest cli args

cli/tests/integration/args.rs, cli/tests/integration/common.rs, cli/tests/integration/request.rs, cli/tests/integration/response.rs
Add a macro for generating the core wasm and component versions of a test, and
modify the `.adapt_component` builder function on `Test` to accept a bool. This
simplifies modifying existing tests to support components by doing the work of
abstracting out the body in a macro.
=> Rework component testing support to make test updates easier

cli/tests/integration/common.rs, cli/tests/integration/logging.rs, lib/src/execute.rs, lib/src/linking.rs, lib/src/logging.rs, lib/src/session.rs
Some integration tests need to capture log output in order to verify that logging endpoints work correctly from guests, but it's also potentially useful for people using Viceroy as a library.
The previous way that the integration tests did this was not reliable when multiple tests ran in parallel, because there was only one global hook for capturing logs. Exposing this as a configuration option on execution contexts instead allows each test to set independent capture buffers.
I guess this should be considered a breaking API change since `viceroy_lib::logging::LOG_WRITER` was exported publicly from the crate.
=> Allow capturing logging endpoint messages

Cargo.lock, cli/tests/integration/common.rs, cli/tests/trap-test/Cargo.lock, cli/tests/trap-test/src/main.rs, lib/Cargo.toml, lib/compute-at-edge-abi/compute-at-edge.witx, lib/src/component/http_req.rs, lib/src/execute.rs, lib/src/service.rs, lib/src/session.rs, lib/src/wiggle_abi/req_impl.rs, test-fixtures/Cargo.lock, test-fixtures/Cargo.toml, test-fixtures/src/bin/downstream-req.rs
A customer noticed when trying to use the Rust SDK's `Request::get_server_ip` method that the  `downstream_server_ip_addr` hostcall is not yet implemented in Viceroy. This PR adds support for it. I've also updated the SDK version used in the tests to be the latest release.
=> Add `downstream_server_ip_addr` hostcall

crates/adapter/src/fastly/core.rs, lib/compute-at-edge-abi/compute-at-edge.witx, lib/src/cache.rs, lib/src/component/http_resp.rs, lib/src/lib.rs, lib/src/upstream.rs, lib/src/wiggle_abi/req_impl.rs, lib/src/wiggle_abi/resp_impl.rs, lib/wit/deps/fastly/compute.wit
This adds the `get_addr_dest_ip` and `get_addr_dest_port` hostcalls which will be part of the upcoming SDK release. They allow getting the IP and port used to connect to a backend from the `ResponseHandle`.
There is a difference in behaviour here worth calling out: in Compute, this is only currently supported when using `.set_pass(true)` on the `Request`. Since Viceroy doesn't have any concept of caching/direct pass at the moment, I wasn't sure whether I should add enough code to check whether the guest code had at least requested direct pass or not, and limit support so that things match what applications deployed to Compute will see.
=> Add `get_addr_dest_{ip,port}` hostcalls

.github/workflows/release.yml, .github/workflows/test.yml
Reverts a change made in #388 that prevented builds being generated for macOS amd64 machines.
=> Release on macOS amd64

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
This release resolves an issue preventing users on macOS amd64 machines from using Viceroy via the Fastly CLI.
PR created following the release process as documented in `docs/RELEASING.md`.
=> 🎁 Prepare release v0.10.1

.github/workflows/release.yml, .github/workflows/test.yml
The previous change in #388 inadvertently raised the required minimum glibc versions for our Linux release binaries. This patch returns the runners to 20.04 for the moment, though testing against multiple `ubuntu` runners may be added in the future.
=> ⬅ Switch back to `ubuntu-20.04` runners for CI and release

CHANGELOG.md, cli/tests/integration/kv_store.rs, lib/src/config/object_store.rs, lib/src/error.rs, test-fixtures/data/json-kv_store.json
It's very practical to be able to keep all your local configuration in separate files, if they are e.g. generated by automatic scripts. This extends the `fastly.toml` `kv_store` configuration to accept either the current inline API or a new `file` and `format` table, that allows loading of an external JSON file.
Part of #364
=> Allow specifying top-level `file` and `format` for KVStore

.github/workflows/test.yml
There seems to be something weird with with how we're using the GitHub Action cache that both @kpfleming and I have hit today that's breaking the test CI. I've had a good experience using [mozilla-actions/sccache-action](https://github.com/mozilla-actions/sccache-action) elsewhere, so I've made this PR to try out using it instead of saving and restoring the `target/` directories. I've adjusted `actions/cache` to only save `~/.cargo/registry`.
=> Use mozilla-actions/sccache-action for caching builds

lib/src/execute.rs
Emit the response status code when emitting stats about the request that was handled. Additionally, move the tracing span so that it covers all messages emitted for request handling, not just `run_guest`.
Here's a sample of what the new output looks like (when `-v` is passed):
```
2024-08-14T22:41:59.706626Z  INFO Listening on http://127.0.0.1:7676
2024-08-14T22:42:03.128146Z  INFO request{id=0}: handling request GET http://localhost:7676/
2024-08-14T22:42:03.128951Z  INFO request{id=0}: request completed using 1.1 MB of WebAssembly heap
2024-08-14T22:42:03.128999Z  INFO request{id=0}: request completed in 756µs
2024-08-14T22:42:03.129141Z  INFO request{id=0}: response status: 200
```
=> Emit the status code for responses, in addition to other stats

lib/src/execute.rs
Otherwise we end up with log messages that include multiple request
IDs when we are processing concurrent requests.
=> split info spans when logging request IDs

lib/src/component/async_io.rs, lib/src/component/backend.rs, lib/src/component/cache.rs, lib/src/component/compute_runtime.rs, lib/src/component/config_store.rs, lib/src/component/device_detection.rs, lib/src/component/dictionary.rs, lib/src/component/erl.rs, lib/src/component/geo.rs, lib/src/component/http_body.rs, lib/src/component/http_req.rs, lib/src/component/http_resp.rs, lib/src/component/http_types.rs, lib/src/component/kv_store.rs, lib/src/component/log.rs, lib/src/component/mod.rs, lib/src/component/object_store.rs, lib/src/component/purge.rs, lib/src/component/secret_store.rs, lib/src/component/types.rs, lib/src/component/uap.rs, lib/src/linking.rs
Switch to implementing component traits on `ComponentCtx` instead of `Session`. This gives us access to the resource table, which will allow us to support the use of resources like the new `fastly:api/kv-store/lookup-result` resource.
The change was pretty mechanical:
* all component traits are now implemented on `ComponentCtx`
* many uses of `self` needed to change to `self.session`
cc @computermouth
=> Implement component traits on ComponentCtx

cli/tests/integration/inspect.rs, cli/tests/integration/main.rs, lib/src/wiggle_abi/req_impl.rs, test-fixtures/Cargo.lock, test-fixtures/Cargo.toml, test-fixtures/src/bin/inspect.rs
This fixes an issue @junichi-hata reported with using the `inspect` hostcall. I called `GuestPtr::array` with the full length of the buffer the guest had allocated instead of the length of the source slice, which results in `copy_from_slice` returning a `SliceLengthsDiffer` error when used. This fixes which length is used, and, now that the updated SDK is available, adds a test to exercise the `inspect` path.
=> Fix bug in `inspect` implementation and add a test

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
Updates lockfiles and `CHANGELOG.md` per [the release instructions](https://github.com/fastly/Viceroy/blob/main/doc/RELEASING.md).
=> 📦 Prepare v0.12.0 release

cli/tests/integration/secret_store.rs, lib/src/config/secret_store.rs, lib/src/error.rs, test-fixtures/data/json-secret_store.json, test-fixtures/src/bin/secret-store.rs
This uses the same format as for the KV store, introduced in #365.
Fixes #364.
=> add support for reading secrets from a JSON file

crates/adapter/src/fastly/core.rs, lib/src/component/error.rs, lib/src/component/kv_store.rs, lib/wit/deps/fastly/compute.wit
First attempt at implementing the component hostcalls in viceroy.
Keeping as draft until https://github.com/fastly/Viceroy/pull/427 is merged, as there's some component changes in that branch as well.
=> Implement the component-side hostcalls for KV Store

lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/http-cache.witx, lib/src/linking.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/http_cache.rs, lib/src/wiggle_abi/req_impl.rs
Adds the hostcalls for the forthcoming HTTP cache API, stubbed as "not available".
This will enable releasing the Rust SDK using these features. For the sake of time, the Component bindings are left for follow up.
=> Stub new HTTP cache hostcalls (witx only)

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
Updates lockfiles and CHANGELOG.md per [the release instructions](https://github.com/fastly/Viceroy/blob/main/doc/RELEASING.md).
=> 🎁 Prepare release v0.12.2

.gitignore, cli/tests/integration/kv_store.rs, lib/src/object_store.rs
Conform to the restrictions in
https://docs.fastly.com/en/guides/working-with-kv-stores#limitations-and-considerations
Partially fixes https://github.com/fastly/cli/issues/1383
=> Update KV store key naming restrictions

lib/src/linking.rs, test-fixtures/src/bin/env-vars.rs
See https://docs.fastly.com/en/guides/working-with-staging for more on staging.
This environment variable [indicates](https://docs.fastly.com/en/guides/working-with-staging#compute) the request is running in the staging environment. Viceroy is not "the staging environment", so we return 0. (Admittedly, it's also not running in production...)
Relevant to #336.
=> Include FASTLY_IS_STAGING environment variable

lib/src/linking.rs, test-fixtures/src/bin/env-vars.rs
Pursuant to #336.
If we were to implement #336 today, this test would fail off the bat:
not because the implementation is incorrect, but because the test
does not verify correct behavior, only the current behavior.
That is, it is a change-detector test [1].
A directed test should admit any correct implementation.
To that end, refactor so that this tests presence and (where applicable)
structure of environment variables, but does not validate that they have
particualr values. (Except in the case of `FASTLY_HOSTNAME`,
which has one correct value for Viceroy.)
[1]: https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html
=> Accept all valid environment variables

.github/workflows/release.yml, .github/workflows/test.yml
Per https://github.com/actions/runner-images/issues/11101, Github is turning down 20.04 actions, and is issuing brownouts that cause CI failures. (I saw it fail the 20.04 matrix steps and the package-check step on my PRs.)
To keep the CI flowing, remove 20.04 from the matrices, and upgrade package-check to 24.04.
=> Remove ubuntu-20.04 from CI

cli/src/main.rs, cli/src/opts.rs, lib/src/execute.rs, lib/src/lib.rs
This change matches the configuration support for guest profling provided by wasmtime and is useful for integrators making use of guest profiling to be able to get a more fine/coarse grained view of the execution of their services (and also balance data generated, overhead, etc.).
In preparing to submit this change for review, I first saw that there is an alternative implementation of this with
https://github.com/fastly/Viceroy/pull/437, doing mostly the same things in a slightly different form.
=> Guest Profile sample period configuration support

cli/tests/integration/kv_store.rs, lib/src/config/object_store.rs, lib/src/error.rs, test-fixtures/data/json-kv_store.json, test-fixtures/src/bin/kv_store.rs
This PR adds support for an optional `metadata` string field in `[local_server.kv_stores]` of the `fastly.toml` config file.
It's used something like this:
```toml
[[local_server.kv_stores.example_store]]
key = "entry"
data = "this is some data"
metadata = "this is some metadata"
```
Now it can be accessed, e.g., in a JavaScript application:
```javascript
const entry = await kv.get('entry');
console.log('metadata', entry.metadataText());    // this is some metadata
console.log('text', await entry.text());          // this is some data
```
As described on [KV Store Item - Metadata](https://www.fastly.com/documentation/reference/api/services/resources/kv-store-item/#metadata), `metadata` can only be a UTF-8 string up to 2000 characters, so I didn't add support for non-strings or for …
=> Add support for "metadata" field for local_server KV Store entry configs in fastly.toml

CHANGELOG.md, Cargo.lock, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, lib/Cargo.toml, test-fixtures/Cargo.lock
Updates lockfiles and CHANGELOG.md per [the release instructions](https://github.com/fastly/Viceroy/blob/main/doc/RELEASING.md).
I have checked that `make ci` succeeds locally.
=> Prepare release v0.12.4

cli/tests/integration/cache.rs, lib/proptest-regressions/cache.txt, lib/src/cache.rs, lib/src/cache/store.rs, lib/src/cache/variance.rs, lib/src/component/cache.rs, lib/src/wiggle_abi/cache.rs, test-fixtures/src/bin/cache.rs
Implement two important metadata items:
- `max_age` and initial age, for computing staleness
- request/response headers and `vary_by`
And along with that... implement lookup according to HTTP's vary semantics, adding another layer to the internal data structures.
=> Age and vary_by

cli/tests/integration/cache.rs, lib/src/cache.rs, lib/src/cache/store.rs, lib/src/component/cache.rs, lib/src/component/error.rs, lib/src/error.rs, lib/src/session.rs, lib/src/wiggle_abi/cache.rs, test-fixtures/src/bin/cache.rs, test-fixtures/src/bin/cache_transactional.rs
Start implementing the transactional side of the core cache API.
Transactions begin with a `transaction_lookup` or `transaction_lookup_async`. When the `CacheBusyHandle` is `await`ed, it either returns a result immediately; returns an obligation indicating "you should fulfill this"; or blocks, until the obligatee abandons or fulfills their obligation.
NB, the implementation of `cancel` here matches a recent change to Fastly's Compute Platform. Previously, `close(BusyHandle)` would block until the obligation was fulfilled or granted to the closer; now, `close` doesn't block. This shouldn't really matter to anyone other than making e.g. timeouts to origin fail in better ways.
=> Transactional cache API, missing some options

lib/src/cache.rs, lib/src/cache/store.rs, lib/src/collecting_body.rs, lib/src/component/cache.rs, lib/src/wiggle_abi/cache.rs, test-fixtures/src/bin/cache.rs
Support `known_length` insert option.
Generate an error on body read if the `known_length` provided does not match the total number of bytes written.
(The fixture test passes on the compute platform and in Viceroy.)
=> :straight_ruler:  Known length option for core cache

cli/src/main.rs, cli/tests/integration/common.rs, lib/src/component/kv_store.rs, lib/src/component/object_store.rs, lib/src/component/shielding.rs, lib/src/downstream.rs, lib/src/execute.rs, lib/src/service.rs, lib/src/session.rs, lib/src/wiggle_abi.rs, lib/src/wiggle_abi/kv_store_impl.rs, lib/src/wiggle_abi/obj_store_impl.rs, lib/src/wiggle_abi/shielding.rs
I was going to add another argument to `Session::new` locally, but realized that at this point it would probably be better to just pass in an `Arc<ExecuteCtx>`. This PR replaces the cloned `Arc` references that get passed to `Session::new` with a single clone of `Arc<ExecuteCtx>`, and updates the `Session` methods to access things through it instead.
Since I've updated `ExecuteCtx::new` to now return an `Arc`, I have moved the `.with_*(mut self, ...)` methods out of `ExecuteCtx` in e08aed3 and into an explicit builder type with a `.finish()` method that returns the wrapped `Arc`, so that the `cli/` code can still use them in a straightforward way.
=> Store `ExecuteCtx` reference in `Session` in place of multiple `Arc`s

lib/src/body.rs
- Process more chunks if we receive just the gzip header
Addresses https://github.com/fastly/Viceroy/issues/479
=> fix(body): skip empty chunks during gzip decoding

lib/src/body.rs, lib/src/cache.rs, lib/src/cache/store.rs, lib/src/component/cache.rs, lib/src/wiggle_abi/cache.rs, test-fixtures/src/bin/cache.rs, test-fixtures/src/bin/expects-hello.rs, test-fixtures/src/bin/write-and-read-body.rs
I had missed this; but some of the "range request" tests uncovered that I had missed it.
- Address several lints
- Sync tests with internal copy
- Test and implement insert_and_stream_back
=> Support execute_and_stream_back

CHANGELOG.md, cli/src/main.rs, cli/src/opts.rs, lib/src/body_tee.rs, lib/src/component/http_req.rs, lib/src/downstream.rs, lib/src/error.rs, lib/src/execute.rs, lib/src/lib.rs, lib/src/pushpin.rs, lib/src/session.rs, lib/src/session/downstream.rs, lib/src/wiggle_abi/req_impl.rs
This PR adds Viceroy code and hostcall implementations to support the hostcalls `fastly_http_req#redirect_to_grip_proxy` and `fastly_http_req#redirect_to_grip_proxy_v2`.
It adds a new runtime command-line flag, `--local-pushpin-port=<port>` that enables this feature.
This pull request introduces the foundational support within Viceroy for proxying requests to a local Pushpin instance. This enables developers to locally test Fastly Compute services that use real-time features like HTTP streaming or WebSockets-over-HTTP, which are powered by Fanout/Pushpin.
Specifically, this change implements the host-side logic for the following ABI functions: `fastly_http_req#redirect_to_grip_proxy` and `fastly_http_req#redirect_to_grip_proxy_v2`
When a guest module calls one of these functions, Viceroy …
=> feat: Add Pushpin proxying support for local testing

lib/compute-at-edge-abi/compute-at-edge.witx, lib/compute-at-edge-abi/http-cache.witx, lib/compute-at-edge-abi/typenames.witx
To prepare for more regularly keeping Viceroy's interfaces up to date, this updates to the latest version of the witx interfaces.
Other than the addition of the backend_name field to the HTTP cache lookup options struct, this just contains comment updates and some minor code movement.
=> Update to the latest version of the witx files.

lib/src/wiggle_abi/http_downstream.rs, test-fixtures/src/bin/downstream-req.rs
This fixes a bug in Viceroy's implementation of the `fastly_http_downstream::downstream_compliance_region` hostcall, which used the `region_max_len` value with `GuestMemory::copy_from_slice`, a method that expects the input and output slices to precisely match in length. It now uses `region_len` as it should.
=> Fix implementation of `downstream_compliance_region` hostcall

lib/src/component/mod.rs
This makes it possible to enable tracing for WIT function calls.
=> Enable tracing in the WIT bindings.

Cargo.lock, cli/Cargo.toml
serial_test and tracing-futures are not used by the cli. tls-listener is only used by a test, so it can be a dev-dependency.
=> Trim unneeded dependencies.

CHANGELOG.md, Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/tests/trap-test/Cargo.lock, doc/RELEASING.md, test-fixtures/Cargo.lock
Updates `CHANGELOG` and lockfiles per [`RELEASING.md`](https://github.com/fastly/Viceroy/blob/main/doc/RELEASING.md).
Verified that `make ci` succeeds locally.
=> Prepare release v0.14.3

.github/workflows/test.yml
Per https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
=> Remove deprecated `macos-13` runners from CI matrix
